# Generated by Django 4.1.7 on 2023-02-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('quantify', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_product', models.ImageField(upload_to='')),
            ],
        ),
    ]
