# Generated by Django 4.1.7 on 2023-02-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_sales',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
