# Generated by Django 4.1.7 on 2023-02-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_amount_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_sales',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
