# Generated by Django 4.1.7 on 2023-02-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_amount_sales_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
