# Generated by Django 4.1.7 on 2023-02-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_image_product1_product_image_product2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
