# Generated by Django 4.1.7 on 2023-02-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(help_text='Type your password', max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
