# Generated by Django 4.1.7 on 2023-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
