# Generated by Django 4.1.7 on 2023-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_register_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
