# Generated by Django 4.1.7 on 2023-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_register_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
