# Generated by Django 4.1.7 on 2023-02-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_register_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
