# Generated by Django 4.1.7 on 2023-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_register_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
