# Generated by Django 4.1.7 on 2023-02-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_general_info_user_delete_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GENERAL_INFO_USER',
        ),
    ]
