# Generated by Django 4.1.7 on 2023-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartdatabase',
            name='url_product',
        ),
        migrations.AddField(
            model_name='shoppingcartdatabase',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
